### ISSUE TITLE
club leagues shows incorrect position.

### ISSUE THREAD

**Issue by PhilChett** [robchett/uknxcl#15]
![pos](https://cloud.githubusercontent.com/assets/17462921/13469993/b8cceba2-e0a1-11e5-9efa-73264d765e53.JPG)

**Comment by robchett** [comment]
Can't they all be winners?

**Comment by PhilChett** [comment]
did you want a sensible answer to that? :-)))

**Comment by robchett** [comment]
Na, that would be boring.

Fixed.
