### ISSUE TITLE
UKNXCL does not support the new IGC date format

### ISSUE THREAD

**Issue by rnhunt** [robchett/uknxcl#4]
The existing old format is (for example) HFDTE240216, however the new format being rolled out is HFDTEDATE:240216 with optional flight number following a comma such as ,01.  The DATE is also optional explanatory text I believe (e.g. could be HFDTE:240216).

The new format not supported in https://github.com/robchett/igc_parser/blob/master/coordinate_set.c

**Comment by rnhunt** [comment]
Latest IGC spec btw at http://www.fai.org/downloads/igc/FRTS_4

**Comment by robchett** [comment]
Support now added, should have covered all cases.
